# toml-docs-start main
[main]
    separator = ""
    description = ""
    canonifyAssetsURLs = false
    endorse = false
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    titleCase = false
    [main.padding]
        x = 4
        y = 4
    [main.internalLinks]
        validate = true
        pretty = false
    [main.externalLinks]
        cue = false
        tab = false
    [main.build]
        transpiler = "dartsass"
        silenceDeprecations = true
    [main.colorMode]
        enabled = true
        modes = ["light", "dark"]
        toggle = false
# toml-docs-end main

[navigation]
    anchor = true
    logo = "/static/img/logo_icon.svg"
    logo-mode = false
    logo-align = "center"
    logo-height = 30
    color = "body"
    fixed = true
    overlay = false
    overlayMode = "dark"
    horizontal = false
    offset = "5.7rem"
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"
    startLevel = 2
    endLevel = 3
    maxNumHeadings = 9
    [navigation.padding]
        x = 4
        y = 4
    [navigation.search]
        enabled = true
        modal = true
  
[favicon]
    logo = "/img/favicon.png"
    sizes = [16, 32, 48]

# toml-docs-start theme-colors
[style]
    primary = "#d43900"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
# toml-docs-end theme-colors
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
# toml-docs-start font
    themeFont = "Inter"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" # external path
    themeFontPath = "/fonts" # local path
    fontSizeBase = "1rem" # assumes the browser default, typically '16px'
# toml-docs-end font
# toml-docs-start build
    purge = false
# toml-docs-end build