[home]
    # sections = ["blog", "projects"]
    sections = ["blog"]
    fullCover = false
    centerHeadline = false
    style = ""
    [home.feature]
        orientation = "horizontal"
        color = "primary"
        width = 4
        align = "start"

[navigation]
    anchor = true
    logo = "./img/alof.svg"
    color = "body"
    fixed = true
    horizontal = false
    offset = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"

[sections]
    [sections.blog]
        title = "Blog"
        sort = "date"
        reverse = true
        cols = 3
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom card-body-margin"
        homepage = 3
        separator = true
    [sections.projects]
        title = "Projects"
        layout = "card"
        sort = "title"
        reverse = false
        nested = true
        cols = 1
        background = "body-tertiary"
        color = "body"
        padding = "3"
        header = "none"
        footer = "tags"
        orientation = "horizontal-sm"
        style = "border-1 card-emphasize"
        homepage = 3
        separator = false

[favicon]
    logo = "./img/favicon.png"
    sizes = [16, 32, 48]
