# toml-docs-start main
[main]
    separator = ""
    description = ""
    enableDarkMode = true
    modes = ["light", "dark"]
    canonifyAssetsURLs = false
    endorse = false
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    [main.externalLinks]
        cue = false
        tab = false
    [main.build]
        transpiler = "libsass"
# toml-docs-end main

[home]
    # sections = ["blog", "projects"]
    sections = ["blog", "projects", "features", "users"]
    fullCover = false
    centerHeadline = false
    style = ""
    [home.feature]
        orientation = "horizontal"
        color = "primary"
        width = 4
        align = "start"

[navigation]
    anchor = true
    logo = "https://raw.githubusercontent.com/stanceyan/afblog/main/static/img/logo_icon.svg"
    color = "body"
    fixed = true
    horizontal = false
    offset = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"

[sections]
    [sections.blog]
        title = "Blòg"
        sort = "date"
        reverse = true
        cols = 5
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom card-body-margin"
        homepage = 5
        separator = true
    [sections.projects]
        title = "Pwojè"
        layout = "card"
        sort = "title"
        reverse = false
        nested = true
        cols = 1
        background = "body-tertiary"
        color = "body"
        padding = "3"
        header = "none"
        footer = "tags"
        orientation = "horizontal-sm"
        style = "border-1 card-emphasize"
        homepage = 3
        separator = false
    [sections.features]
        title = "Développez votre compréhension du droit de la fonction publique."
        layout = "list"
        sort = "weight"
        reverse = false
        style = "justify-content-center"
    [sections.users]
        title = "Discover"
        layout = "nav"
        sort = "weight"
        reverse = false
        background = "body-tertiary"
        color = "primary"
        style = "justify-content-center"
        pane = "persona"
        type = "pills"
        width = 50
        vertical = false
        
[favicon]
    logo = "/img/favicon.png"
    sizes = [16, 32, 48]

# toml-docs-start theme-colors
[style]
    primary = "#d43900"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
# toml-docs-end theme-colors
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
# toml-docs-start font
    themeFont = "Inter"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" # external path
    themeFontPath = "/fonts" # local path
    fontSizeBase = "1rem" # assumes the browser default, typically '16px'
# toml-docs-end font
# toml-docs-start build
    purge = false
# toml-docs-end build