title = 'Alofonksyone'
copyright = "Copyright © 2024 Alo Fonksyonè Blòg."
enableGitInfo = true

# additional settings
baseURL = 'https://example.org/'
canonifyURLs = false
# uglyURLs = true
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true

timeout = "180s"

languageCode = 'en-us'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# toml-docs-start lang-param
[params.head]
tagline = "A Hugo Theme"
[params.social]
title = "Swiv nou"
caption = "Nou pibliye sou paj rezo sosyo sa yo tou"
[params.footer]
# license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."
# toml-docs-end lang-param
[params.sections.blog]
reference = "More Posts"
[params.sections.projects]
reference = "More Projects"


[outputs]
home = ["HTML", "RSS", "REDIR"]

[build]
  writeStats = true
  
[taxonomies]
  tag = 'tags'

[module]
  [[module.mounts]]
      source = 'content'
      target = 'content'
  [[module.mounts]]
      source = 'static'
      target = 'static'
  [[module.mounts]]
      source = 'layouts'
      target = 'layouts'
  [[module.mounts]]
      source = 'data'
      target = 'data'
  [[module.mounts]]
      source = 'assets'
      target = 'assets'
  [[module.mounts]]
      source = 'archetypes'
      target = 'archetypes'


  [[module.imports]]
  path = 'github.com/gethinode/hinode'
