title = 'Alofonksyone'
copyright = "Copyright © 2024 Alofonksyone Blog."
enableGitInfo = true

# additional settings
baseURL = 'https://example.org/'
canonifyURLs = false
uglyURLs = true
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true

timeout = "180s"

languageCode = 'en-us'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[outputs]
home = ["HTML", "RSS", "REDIR"]

[build]
  writeStats = true
  
[taxonomies]
  tag = 'tags'

[module]
  [[module.mounts]]
      source = 'content'
      target = 'content'
  [[module.mounts]]
      source = 'static'
      target = 'static'
  [[module.mounts]]
      source = 'layouts'
      target = 'layouts'
  [[module.mounts]]
      source = 'data'
      target = 'data'
  [[module.mounts]]
      source = 'assets'
      target = 'assets'
  [[module.mounts]]
      source = 'archetypes'
      target = 'archetypes'


  [[module.imports]]
  path = 'github.com/gethinode/hinode'
